const commando = require('discord.js-commando');
const random = require('../../util/random');

var jobies = [
    "https://i.imgur.com/iF8Nfe7.jpg",
    "https://i.imgur.com/hfI5P7J.jpg",
    "https://i.imgur.com/TeTBLKa.jpg",
    "https://i.imgur.com/0wQhuNi.jpg",
    "https://i.imgur.com/Zo6KYho.jpg",
    "https://i.imgur.com/Kv0hWp5.jpg",
    "https://i.imgur.com/G4qrrIZ.jpg",
    "https://i.imgur.com/eTsZ7DY.jpg",
    "https://i.imgur.com/ipMulEj.jpg",
    "https://i.imgur.com/ykyKSgA.jpg",
    "https://i.imgur.com/6qzaXVo.jpg",
    "https://i.imgur.com/2U3uVAl.jpg",
    "https://i.imgur.com/xKFQoGJ.jpg",
    "https://i.imgur.com/MQgdgmy.jpg",
    "https://i.imgur.com/94njXSy.jpg",
    "https://i.imgur.com/DDt8jUs.jpg",
    "https://i.imgur.com/Js9D7PN.jpg",
    "https://i.imgur.com/sCULkqZ.jpg",
    "https://i.imgur.com/cXYApnL.jpg",
    "https://i.imgur.com/okTz0NO.jpg",
    "https://i.imgur.com/PBRAWxk.jpg",
    "https://i.imgur.com/QCagt47.jpg",
    "https://i.imgur.com/Fe7Shn9.jpg",
    "https://i.imgur.com/bzS3YIl.jpg",
    "https://i.imgur.com/bHtLUux.jpg",
    "https://i.imgur.com/Jwoq5Py.jpg",
    "https://i.imgur.com/Dfio7Gc.jpg",
    "https://i.imgur.com/1dHd9N1.jpg",
    "https://i.imgur.com/aHcWhMW.jpg",
    "https://i.imgur.com/KY4d4mX.jpg",
    "https://i.imgur.com/CuNqdgC.jpg",
    "https://i.imgur.com/pNm7J3i.jpg",
    "https://i.imgur.com/Q985lhQ.jpg",
    "https://i.imgur.com/lMbr02b.jpg",
    "https://i.imgur.com/ZQWW5a2.jpg",
    "https://i.imgur.com/Colvqr9.jpg",
    "https://i.imgur.com/sJM9tv0.jpg",
    "https://i.imgur.com/bjLjT40.jpg",
    "https://i.imgur.com/aM72wRQ.jpg",
    "https://i.imgur.com/uBBOMk5.jpg",
    "https://i.imgur.com/YzmHZ0M.jpg",
    "https://i.imgur.com/gsiJJoA.jpg",
    "https://i.imgur.com/Byk6T5c.jpg",
    "https://i.imgur.com/FOb0iCz.jpg",
    "https://i.imgur.com/HXucFZ6.jpg",
    "https://i.imgur.com/HoHgzMs.jpg",
    "https://i.imgur.com/BEGvTkn.jpg",
    "https://i.imgur.com/y9p9zkR.jpg",
    "https://i.imgur.com/emeEEBH.jpg",
    "https://i.imgur.com/94rvvwT.jpg",
    "https://i.imgur.com/doP2LpL.jpg",
    "https://i.imgur.com/5G5Z9Ng.jpg",
    "https://i.imgur.com/mkzcjOV.jpg",
    "https://i.imgur.com/JJUmxKJ.jpg",
    "https://i.imgur.com/8E1Yxr3.jpg",
    "https://i.imgur.com/no1kF2P.jpg",
    "https://i.imgur.com/XQ3Kyhs.jpg",
    "https://i.imgur.com/d4EE5Ns.jpg",
    "https://i.imgur.com/GKXCH31.jpg",
    "https://i.imgur.com/53057zf.jpg",
    "https://i.imgur.com/Opw7XIP.jpg",
    "https://i.imgur.com/Vw7K9K9.jpg",
    "https://i.imgur.com/lP4bgjA.jpg",
    "https://i.imgur.com/IjKuY76.jpg",
    "https://i.imgur.com/ZxCX3EL.jpg",
    "https://i.imgur.com/mH1FvUj.jpg",
    "https://i.imgur.com/NosOmgo.jpg",
    "https://i.imgur.com/YxzNNxR.jpg",
    "https://i.imgur.com/11xcWja.jpg",
    "https://i.imgur.com/xqHdYJt.jpg",
    "https://i.imgur.com/K6OvKle.jpg",
    "https://i.imgur.com/27Iym8K.jpg",
    "https://i.imgur.com/VI5K9Mf.jpg",
    "https://i.imgur.com/dYWKXZk.jpg",
    "https://i.imgur.com/YDSPUIi.jpg",
    "https://i.imgur.com/2teqtTS.jpg",
    "https://i.imgur.com/jvwE9KR.jpg",
    "https://i.imgur.com/w81qqea.jpg",
    "https://i.imgur.com/VBBGQ9L.jpg",
    "https://i.imgur.com/F2ptNgU.jpg",
    "https://i.imgur.com/JQodaTq.jpg",
    "https://i.imgur.com/cyvbvZP.jpg",
    "https://i.imgur.com/sGIXL20.jpg",
    "https://i.imgur.com/xcbMbGP.jpg",
    "https://i.imgur.com/Zn58f5O.jpg",
    "https://i.imgur.com/J5bZ9mc.jpg",
    "https://i.imgur.com/NoJkTd3.jpg",
    "https://i.imgur.com/AP61hXy.jpg",
    "https://i.imgur.com/da2Urb5.jpg",
    "https://i.imgur.com/shLabNS.jpg",
    "https://i.imgur.com/p9zsKsN.jpg",
    "https://i.imgur.com/NTRWDBj.jpg",
    "https://i.imgur.com/ngcQase.jpg",
    "https://i.imgur.com/ApOHFNW.jpg",
    "https://i.imgur.com/ToYOmsg.jpg",
    "https://i.imgur.com/j6bz7ts.jpg",
    "https://i.imgur.com/d3Vg0ux.jpg",
    "https://i.imgur.com/lXGhVFw.jpg",
    "https://i.imgur.com/uv6UllM.jpg",
    "https://i.imgur.com/1riUlgS.jpg",
    "https://i.imgur.com/NTyCR4c.jpg",
    "https://i.imgur.com/vo7Eibx.jpg",
    "https://i.imgur.com/E5LhERD.jpg",
    "https://i.imgur.com/D9t1rr3.jpg",
    "https://i.imgur.com/66FAQwN.jpg",
    "https://i.imgur.com/g9ywUxh.jpg",
    "https://i.imgur.com/m6hLgJt.jpg",
    "https://i.imgur.com/YyUa8kM.jpg",
    "https://i.imgur.com/bnpTTwN.jpg",
    "https://i.imgur.com/AwwuLZR.jpg",
    "https://i.imgur.com/7dlVX0L.jpg",
    "https://i.imgur.com/bfbGvCY.jpg",
    "https://i.imgur.com/xLfJeDC.jpg",
    "https://i.imgur.com/VzVEBJz.jpg",
    "https://i.imgur.com/3Qz1tW5.jpg",
    "https://i.imgur.com/6YwSN2D.jpg",
    "https://i.imgur.com/COOPYdN.jpg",
    "https://i.imgur.com/aSPM4RK.jpg",
    "https://i.imgur.com/11DjhDr.jpg",
    "https://i.imgur.com/Dltdd7Q.jpg",
    "https://i.imgur.com/rxWt1hb.jpg",
    "https://i.imgur.com/TXpM6fn.jpg",
    "https://i.imgur.com/G7NBuZu.jpg",
    "https://i.imgur.com/izwi0B7.jpg",
    "https://i.imgur.com/DlvROQz.jpg",
    "https://i.imgur.com/nluSOUC.jpg",
    "https://i.imgur.com/qCw6txG.jpg",
    "https://i.imgur.com/Fc8cF98.jpg",
    "https://i.imgur.com/MJEL8WQ.jpg",
    "https://i.imgur.com/nGFQUIv.jpg",
    "https://i.imgur.com/yrNDJbc.jpg",
    "https://i.imgur.com/e5Qc7dW.jpg",
    "https://i.imgur.com/4tlafW9.jpg",
    "https://i.imgur.com/138sUaq.jpg",
    "https://i.imgur.com/zkCvGBO.jpg",
    "https://i.imgur.com/6XRqwt1.jpg",
    "https://i.imgur.com/vj5YGvu.jpg",
    "https://i.imgur.com/gFWCKfX.jpg",
    "https://i.imgur.com/OygnaWN.jpg",
    "https://i.imgur.com/ElrhS9n.jpg",
    "https://i.imgur.com/ZfhYAe7.jpg",
    "https://i.imgur.com/bODkoG9.jpg",
    "https://i.imgur.com/CXaJlKg.jpg",
    "https://i.imgur.com/lp9ylCk.jpg",
    "https://i.imgur.com/KFIyolm.jpg",
    "https://i.imgur.com/FMSZYf5.jpg",
    "https://i.imgur.com/KLH8QFU.jpg",
    "https://i.imgur.com/fH1Jqof.jpg",
    "https://i.imgur.com/1O3xB9S.jpg",
    "https://i.imgur.com/TWwVJ0U.jpg",
    "https://i.imgur.com/92l3t3A.jpg",
    "https://i.imgur.com/xuMKbxW.jpg",
    "https://i.imgur.com/Ss0Gk3Y.jpg",
    "https://i.imgur.com/1egVTgL.jpg",
    "https://i.imgur.com/41RMd7y.jpg",
    "https://i.imgur.com/Fk8xIA1.png",
    "https://i.imgur.com/MJbIHGu.jpg",
    "https://i.imgur.com/7acPhzS.jpg",
    "https://i.imgur.com/2NTJ6rm.jpg",
    "https://i.imgur.com/OIkL7gJ.jpg",
    "https://i.imgur.com/VtVAchB.jpg",
    "https://i.imgur.com/6lV8BWP.jpg",
    "https://i.imgur.com/NamMPOQ.jpg",
    "https://i.imgur.com/hLbtjKr.jpg",
    "https://i.imgur.com/k50eOs0.jpg",
    "https://i.imgur.com/Bz2eDM1.jpg",
    "https://i.imgur.com/jkoOvoM.jpg",
    "https://i.imgur.com/mb4Ny3g.jpg",
    "https://i.imgur.com/ZeM0FMt.jpg",
    "https://i.imgur.com/rK4f2GI.jpg",
    "https://i.imgur.com/SGIYhEP.jpg",
    "https://i.imgur.com/GQk3WgJ.jpg",
    "https://i.imgur.com/GR3ODOS.jpg",
    "https://i.imgur.com/LgESBIH.jpg",
    "https://i.imgur.com/pQYtTSG.jpg",
    "https://i.imgur.com/HS00ZWg.jpg",
    "https://i.imgur.com/NSNkj1T.jpg",
    "https://i.imgur.com/ppjhO31.jpg",
    "https://i.imgur.com/WgHU6io.jpg",
    "https://i.imgur.com/6CJlNGg.jpg",
    "https://i.imgur.com/UfZEmwD.jpg",
    "https://i.imgur.com/i8jSAJb.jpg",
    "https://i.imgur.com/GPG7x2W.jpg",
    "https://i.imgur.com/BTHRkWR.jpg",
    "https://i.imgur.com/52TtFKI.jpg",
    "https://i.imgur.com/bucStU8.jpg",
    "https://i.imgur.com/8RQl6q0.jpg",
    "https://i.imgur.com/O7Ldl2b.jpg",
    "https://i.imgur.com/PdHYzxw.jpg",
    "https://i.imgur.com/V5L0Dex.jpg",
    "https://i.imgur.com/bJeXS4g.jpg",
    "https://i.imgur.com/iF9qKC4.jpg",
    "https://i.imgur.com/dL7UQVY.jpg",
    "https://i.imgur.com/CMqSo6l.jpg",
    "https://i.imgur.com/6pmiHXe.jpg"
];

class Spam extends commando.Command {
    constructor(client) {
        super(client, {
            name: "spam",
            group: "simple",
            memberName: "spam",
            description: "summons 3 pictures of jobie, none of them are repeats"
        });
    }

    async run(message, args) {

        let arr = random()

        await message.channel.send(`HI ${message.author}! it seems like you need some extra jobies this time, i'm coming for cuddles but in the mean time i can give you some extra pics that my lovely wife took ` +
            jobies[arr[0]] + " " +
            jobies[arr[1]] + " " +
            jobies[arr[2]]);

    }
}

module.exports = Spam;